use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct OpenApiDocument {
    paths: BTreeMap<String, BTreeMap<String, Operation>>,
}

#[derive(Debug, Deserialize)]
struct Operation {
    tags: Option<Vec<String>>,
    #[serde(rename = "operationId")]
    operation_id: String,
    security: Option<Vec<BTreeMap<String, Vec<serde_yaml::Value>>>>,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let kernel_root = manifest_dir.join("../..");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let openapi_path =
        kernel_root.join("apis/internal-api/intelligence/sdkwork-agent-internal-api.openapi.yaml");

    let yaml = fs::read_to_string(&openapi_path)
        .unwrap_or_else(|error| panic!("failed to read {openapi_path:?}: {error}"));
    let document: OpenApiDocument =
        serde_yaml::from_str(&yaml).expect("failed to parse internal OpenAPI yaml");
    let entries = collect_routes(&document);
    let source = render_routes("INTERNAL_ROUTES", &entries);
    fs::write(out_dir.join("agent_internal_routes.rs"), source)
        .expect("failed to write internal route manifest");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", openapi_path.display());
}

#[derive(Clone)]
struct RouteEntry {
    method: String,
    path: String,
    tag: String,
    operation_id: String,
    auth: String,
}

fn collect_routes(document: &OpenApiDocument) -> Vec<RouteEntry> {
    let mut routes = Vec::new();
    for (path, operations) in &document.paths {
        for (method, operation) in operations {
            let Some(http_method) = normalize_method(method) else {
                continue;
            };
            routes.push(RouteEntry {
                method: http_method.to_owned(),
                tag: operation
                    .tags
                    .as_ref()
                    .and_then(|tags| tags.first())
                    .cloned()
                    .unwrap_or_else(|| "runtime".to_owned()),
                operation_id: operation.operation_id.clone(),
                auth: classify_auth(operation.security.as_ref()),
                path: path.clone(),
            });
        }
    }
    routes
}

fn normalize_method(method: &str) -> Option<&'static str> {
    match method.to_ascii_lowercase().as_str() {
        "get" => Some("Get"),
        "post" => Some("Post"),
        "patch" => Some("Patch"),
        "put" => Some("Put"),
        "delete" => Some("Delete"),
        _ => None,
    }
}

fn classify_auth(security: Option<&Vec<BTreeMap<String, Vec<serde_yaml::Value>>>>) -> String {
    let Some(entries) = security else {
        return "Public".to_owned();
    };
    let mut has_auth_token = false;
    let mut has_access_token = false;
    let mut has_api_key = false;
    for entry in entries {
        for scheme in entry.keys() {
            match scheme.as_str() {
                "AuthToken" => has_auth_token = true,
                "AccessToken" => has_access_token = true,
                "ApiKey" => has_api_key = true,
                _ => {}
            }
        }
    }
    if has_auth_token && has_access_token {
        "DualToken".to_owned()
    } else if has_auth_token || has_api_key {
        "ApiKey".to_owned()
    } else {
        "Public".to_owned()
    }
}

fn render_routes(const_name: &str, routes: &[RouteEntry]) -> String {
    let mut output = String::from(
        "// @generated by sdkwork-routes-agent-internal-manifest/build.rs — do not edit\n\n",
    );
    output.push_str(&format!(
        "pub const {const_name}: &[sdkwork_web_contract::HttpRoute] = &[\n"
    ));
    for route in routes {
        output.push_str(&format!(
            "    sdkwork_web_contract::HttpRoute::new(sdkwork_web_contract::HttpMethod::{}, {:?}, {:?}, {:?}, sdkwork_web_contract::RouteAuth::{}),\n",
            route.method, route.path, route.tag, route.operation_id, route.auth
        ));
    }
    output.push_str("];\n");
    output
}
