apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdkwork-agent-server-data
  labels:
    app.kubernetes.io/name: sdkwork-agent-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
