-- SDKWork Agent Business PostgreSQL Schema Baseline
-- Component: sdkwork-agent-business
-- Domain: intelligence
-- Version: 0.1.0

CREATE TABLE IF NOT EXISTS ai_agent_business (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    owner_user_id BIGINT NOT NULL,
    agent_id VARCHAR(128) NOT NULL,
    code VARCHAR(128) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT,
    manifest_json TEXT NOT NULL,
    default_code_task_intent_json TEXT,
    status SMALLINT NOT NULL,
    visibility SMALLINT NOT NULL,
    tags_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_ai_agent_business_tenant_agent_id UNIQUE (tenant_id, agent_id),
    CONSTRAINT uk_ai_agent_business_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT ck_ai_agent_business_status CHECK (status IN (0, 1, 2, 3, 4)),
    CONSTRAINT ck_ai_agent_business_visibility CHECK (visibility IN (0, 1, 2, 3))
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_business_tenant_org_status_updated
    ON ai_agent_business (tenant_id, organization_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_agent_business_tenant_owner_status
    ON ai_agent_business (tenant_id, owner_user_id, status);

CREATE TABLE IF NOT EXISTS ai_agent_business_audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    agent_business_id BIGINT NOT NULL,
    agent_id VARCHAR(128) NOT NULL,
    action VARCHAR(64) NOT NULL,
    subject_id VARCHAR(128) NOT NULL,
    subject_tenant_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(128),
    trace_id VARCHAR(128),
    payload_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_ai_agent_business_audit_action CHECK (
        action IN ('created', 'updated', 'deleted', 'restored', 'status_changed')
    )
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_business_audit_tenant_agent_created
    ON ai_agent_business_audit_event (tenant_id, agent_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_agent_business_audit_tenant_action_created
    ON ai_agent_business_audit_event (tenant_id, action, created_at DESC);
